### PR TITLE
Allow usage in Rails 7 applications

### PR DESCRIPTION
**Pull request by javierm**
This is the same as #14, which wasn't merged because there was no information about whether the changes had been tested.

I've tested this change on my machine (development environment), [run our test suite including these changes](https://github.com/javierm/consul/actions/runs/8477459031) and tested it on a [staging server](https://staging.consuldemocracy.org/proposals/1-strategic-plan-for-a-100-green-city). Everything seems to be working fine :ok_hand:.

@dgilperez Let me know if there's something else I can do :wink:.

### CODE REVIEW

**Comment by dgilperez** [comment]
Happy to merge and sorry for the delayed response

**Comment by dgilperez** [comment]
I'll do a release if needed, but this is fairly unused project with zero churn - for now you can just fetch master from your Gemfile?

**Comment by javierm** [comment]
@dgilperez No need to apologize! Thank you for your job maintaining this gem all these years :pray:.

From my side, no need to do a release; in the end, last Thursday we decided to [implement the same avatars in our code](https://github.com/consuldemocracy/consuldemocracy/pull/5481). I kept this pull request open in case other people were still using this gem.

**Comment by dgilperez** [comment]
Nice! 

I'm happy to see Consul growing and thriving :)

**Pull request merged**
